## First steps

In this first notebook, we'll take the first steps with Python and check the potential of the notebook. I'll alternate boxes (or "cells") of text and blank cell examples where you can write code and test it. A cell can be used as text (you can also add formulas like $\int_\sqrt{2}^\pi x\sin\left(\frac{1}{x}\right)dx$ in $\LaTeX$) by choosing "Markdown" from the drop-down menu at the top. To execute a cell just press shift + enter. This also applies to specially formatted text cells, like this one. To change it, just double click inside.

The first Python example is a small program to assign two numbers to two variables `p1` and` p2` and then print their sum. 

```
p1 = 987654321
p2 = 123456789
print(p1 + p2)
```

Try typing the above lines in the box below and then press shift + enter, the result should be

`1111111110`

In [1]:
p1 = 987654321
p2 = 123456789
print(p1 + p2)

1111111110


Strings can be formatted via the `print` function. For printing "The sum of 987654321 and 123456789 is 1111111110", write

```
print(f"The sum of {p1} and {p2} is {p1 + p2}")
```

Note the `f` before the string (`f` stands for "formatting") and the objects to be printed enclosed in braces. Try printing the product of `p1` and `p2` below.

In [2]:
print(f"The sum of {p1} and {p2} is {p1 + p2}")


The sum of 987654321 and 123456789 is 1111111110


## Looking back at the prime number checker

We now proceed to an example to introduce control flow. Suppose we want to determine if a given number n is prime, but unlike the previous notebook we don't store its factors. The pseudocode is simple: we need to check, for all integer numbers k from 2 to $\lfloor\sqrt{n}\rfloor$ (why not more?), whether $\frac{n}{k}$ is integer, i.e., whether the division admits a zero remainder.

```
Algorithm: PrimeNumber
Input: n
Output: 1 if n is prime, 0 otherwise
k = 2
while k <= sqrt(n):
  if n is divisible by k
    output 0
  increase k
output 1
```

The Python implementation is also very simple. To encapsulate the algorithm, we define it as a function `PrimeNumber` that takes one number as an input and returns `True` if the number is prime, `False` otherwise.
Note that text between `#` and the end of the line is ignored and can be used for comments.

In [7]:
import math
def PrimeNumber(n):      # Define function PrimeNumber with a single argument n
    for k in range(2, math.floor(math.sqrt(n)) + 1): 
        if n % k == 0:   # The "%" symbol returns the remainder of the 
                         # division n/k, i.e.,
                         # if n = 17 and k = 6 then n % k = 5.
            return False
    return True

    
x = 42
if PrimeNumber(x):
    print(f"{x} is prime")
else:
    print(f"{x} is not prime")


42 is not prime


Now use the definition of `PrimeNumber` above to print all prime numbers from 2 to 1000. All you have to do is run a loop where you check the call to `PrimeNumber` before printing the number.

In [18]:
k=[]
for k in range(2,1001):
    if PrimeNumber(k): # sfrutto la funzione creata prima
        print(k)
v=range(0,4,2)
print(v[0],v[1])

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997
0 2


A few remarks about the `range` function:
* range(10) gives all numbers from 0 to 9;
* range(3,10) gives all numbers from 3 to 9;
* range(3,100,7) gives all numbers from 3 to 100 in steps of 7, i.e.,
3, 10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94.

Therefore, `range(n)` actually doesn't run through $n$ itself, as it stops immediately before. For the loop from 2 to $\sqrt{n}$ (or rather, since we need an integer value, to $\lfloor\sqrt{n}\rfloor$) we need to increase the limit by one to make sure we run through $\lfloor\sqrt{n}\rfloor$, hence the `math.floor(math.sqrt(n))+1`.

Did you notice?

* No semicolon (";") at the end of an instruction, unlike C, C++, or Java;
* No keyword or punctuation to mark the end of a block. In Python, __indentation__ is everything: consecutive lines at the same indentation level are considered a block, ending an indentation is equivalent to ending a for loop, for instance. As an example, the following two snippets do different things:

```
for i in range(3):
   print(i)
   print(42)
```

```
for i in range(3):
   print(i)
print(42)
```

The output of the first snippet will be "0 42 1 42 2 42" (each number on a separate line), while for the second it will be "0 1 2 42". This feature of Python is unique and you should pay attention every time you create a new line.

## Lists

Lists are a simple data structure that stores data of possibly different types. A list containing 1, 2, and "hey!" can be declared like this:

```
l = [1,2,"hey!"]
```

Lists can be concatenated with `+`:

```
l1 = [1,2,3]
l2 = [4,5,6]
print(l1 + l2)
```

A list is represented with its elements separated by a comma and enclosed between square brackets. It can be initialized as `[]` and then amended one element at a time with `amend`. The following code

```
l = []
for i in range(50, 55):
    l.append(i)

print(l)
```

will result in the list `[50,51,52,53,54]`. A list can be referenced just like in many other languages with square brackets, but __note__ that, in Python, indices begin at zero: so the first element of the above list, i.e. 50, is `l[0]`. Negative indices are used to address a list from its other end: `l[-1]` is 54, `l[-2]` is 53, and so on.

The `in` predicate in Python can be used to check if an element is in a list. For instance, if a list is defined as `l = [2, 5, 88, 90909]`, then `2 in l` returns `True`, while `44 in l` returns `False`. Guess what the following snippet does:

In [19]:
l1 = ['Paris', 'Toulouse', 'Milano', 'Torino', 'Roma', 'Munich', 'Frankfurt', 'Edinburgh']
l2 = ['Madrid', 'Paris', 'Berlin', 'Roma', 'Bruxelles', 'Bern', 'Wien']

for city1 in l1:
    if city1 in l2:
        print(city1)

Paris
Roma


## List comprehensions

List comprehensions are a powerful tool in Python to create a list by setting a condition that defines it. For instance, to define a set in maths one can say $S = \{4i^3: i=3,4,\ldots{},10\}$. This is a compact way to define the set $\{108, 256, 500, 864, 1372, 2048, 2916, 4000\}$. In Python, this can be done in a single line:

In [21]:
S = [4*i**3 for i in range(3,11)]
print(S)

[108, 256, 500, 864, 1372, 2048, 2916, 4000]


A few remarks:
* `S` here is a list, not a set, so each element is associated with its position in the list. More important, the index is __not__ related to the value of `i` that generated that number:  `S[0] = 108`, `S[7] = 4000`, and `S[3] = 864`.
* As done before, the `range(3,11)` is necessary for finishing at 10.
* The power operator is `**`, i.e. `3**4` is 81.

Exercise: challenge Python to compute $2^{1000}$.

In [20]:
2**1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

List comprehensions can also be used with conditional predicates. In mathematics, we can define a set $S_1=\{2,\ldots{}, 100\}$ and then define a set $S_2$ with all prime numbers from $S_1$. In Python we can do it as follows: 

In [23]:
S1 = range(2,101)
S2 = [i for i in S1 if PrimeNumber(i)] # seleziona tutti i numeri primi dentro S1
print(S2)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


Here `P` is defined as the list of all `i` in `N` such that `PrimeNumber(i)` returns `True`.

In the next notebook we'll learn Python's dictionaries, which will be very useful in most labs.

As a homework, write a function to compute the first 30 Fibonacci numbers. The Fibonacci sequence consists of numbers $(f_1, f_2, f_3, \ldots{})$ such that $f_1 = f_2 = 1$ and $f_k = f_{k-1} + f_{k-2}$.